using System.Security.Cryptography;
using System.Text;

namespace ReDOS;

/// <summary>What a generated profile should do once the machine has booted.</summary>
internal sealed record LaunchPlan
{
    /// <summary>Host path of the program to run, or null for a bare DOS prompt.</summary>
    internal string? ProgramPath { get; init; }

    internal IReadOnlyList<string> ProgramArgs { get; init; } = [];

    /// <summary>Use CALL, because a batch file otherwise never returns to our exit line.</summary>
    internal bool AsBatch { get; init; }

    /// <summary>Host folder to expose as drive D: when the program was left outside the sandbox.</summary>
    internal string? ExternalMount { get; init; }

    /// <summary>Keep the machine open after the program ends instead of closing the window.</summary>
    internal bool StayOpen { get; init; }

    internal string Title { get; init; } = "ReDOS";
}

/// <summary>
/// Writes the machine description handed to the DOS core. Regenerated on every launch; the parts
/// a user is meant to change live in the sandbox (AUTOEXEC.BAT) or in override files.
/// </summary>
internal static class ProfileBuilder
{
    internal static string Build(LaunchPlan plan)
    {
        AppPaths.EnsureDirectories();
        Sandbox.Ensure();

        var conf = new StringBuilder();
        conf.AppendLine("# Generated by ReDOS. This file is rewritten on every launch -- do not edit.");
        conf.AppendLine("# Persistent tweaks go in:");
        conf.AppendLine($"#   {AppPaths.GlobalOverride}   (every program)");
        conf.AppendLine($"#   {Path.Combine(AppPaths.Overrides, SafeName(plan.Title) + ".conf")}   (this program only)");
        conf.AppendLine("# Startup commands go in the sandbox's own AUTOEXEC.BAT:");
        conf.AppendLine($"#   {Sandbox.AutoexecPath}");
        conf.AppendLine();
        conf.AppendLine("[sdl]");
        conf.AppendLine("fullscreen=false");     // Every program opens in a window; F11+F or alt+enter still toggles.
        conf.AppendLine("autolock=false");
        conf.AppendLine("waitonerror=false");
        conf.AppendLine("output=ttf");           // Text-mode apps look like a normal window; graphics modes switch automatically.
        conf.AppendLine("windowresolution=original");
        conf.AppendLine();
        conf.AppendLine("[ttf]");
        conf.AppendLine("winperc=60");           // Text-mode window covers 60% of the screen: readable, still a window.
        conf.AppendLine();
        conf.AppendLine("[dosbox]");
        conf.AppendLine($"title={plan.Title}");
        conf.AppendLine("startbanner=false");
        conf.AppendLine("quit warning=false");
        conf.AppendLine("memsize=64");
        conf.AppendLine();
        conf.AppendLine("[cpu]");
        conf.AppendLine("core=auto");
        conf.AppendLine("cputype=auto");
        conf.AppendLine("cycles=auto");
        conf.AppendLine();
        conf.AppendLine("[dos]");
        conf.AppendLine("lfn=true");
        conf.AppendLine("ver=7.1");
        conf.AppendLine();
        conf.AppendLine("[render]");
        conf.AppendLine("aspect=true");
        conf.AppendLine();

        AppendOverride(conf, AppPaths.GlobalOverride);
        AppendOverride(conf, Path.Combine(AppPaths.Overrides, SafeName(plan.Title) + ".conf"));

        conf.AppendLine("[autoexec]");
        conf.AppendLine("@echo off");
        conf.AppendLine($"mount c \"{Sandbox.Root}\" -q");
        if (plan.ExternalMount is not null)
            conf.AppendLine($"mount d \"{plan.ExternalMount}\" -q");

        conf.AppendLine("c:");
        conf.AppendLine("if exist C:\\AUTOEXEC.BAT call C:\\AUTOEXEC.BAT");

        if (plan.ProgramPath is not null)
        {
            string driveLetter = plan.ExternalMount is not null && !Sandbox.Contains(plan.ProgramPath) ? "d" : "c";
            string directory = DosDirectoryOf(plan.ProgramPath, driveLetter);

            conf.AppendLine($"{driveLetter}:");
            conf.AppendLine($"cd \\{directory}".TrimEnd('\\'));
            conf.AppendLine(BuildCommand(plan));
        }

        conf.AppendLine(plan.StayOpen || plan.ProgramPath is null ? "" : "exit");

        string profilePath = Path.Combine(
            AppPaths.Profiles,
            SafeName(plan.Title) + "-" + ShortHash(plan.ProgramPath ?? "prompt") + ".conf");
        File.WriteAllText(profilePath, conf.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return profilePath;
    }

    /// <summary>Directory part of a program's DOS path, relative to the root of its drive.</summary>
    private static string DosDirectoryOf(string hostPath, string driveLetter)
    {
        string hostDir = Path.GetDirectoryName(Path.GetFullPath(hostPath)) ?? "";
        if (driveLetter == "c" && Sandbox.Contains(hostPath))
        {
            string dosPath = Sandbox.ToDosPath(hostDir);
            return dosPath.Length > 3 ? dosPath[3..] : "";
        }

        // Drive D: is mounted at the program's own folder, so the program sits at its root.
        return "";
    }

    /// <summary>
    /// DOS can only type what fits in 8.3, so prefer the filesystem's short alias and fall back to
    /// the real name (the core's long-filename support covers the rest).
    /// </summary>
    private static string BuildCommand(LaunchPlan plan)
    {
        string name = Path.GetFileName(plan.ProgramPath!);
        string? shortPath = Native.TryGetShortPath(plan.ProgramPath!);
        if (shortPath is not null) name = Path.GetFileName(shortPath);

        var command = new StringBuilder();
        if (plan.AsBatch) command.Append("call ");
        command.Append(name.Contains(' ') ? $"\"{name}\"" : name);

        foreach (string arg in plan.ProgramArgs)
            command.Append(' ').Append(arg.Contains(' ') ? $"\"{arg}\"" : arg);

        return command.ToString();
    }

    private static void AppendOverride(StringBuilder conf, string path)
    {
        if (!File.Exists(path)) return;
        try
        {
            string body = File.ReadAllText(path);
            if (body.Contains("[autoexec]", StringComparison.OrdinalIgnoreCase))
            {
                // An override must not hijack the launch command; ignore its autoexec section.
                body = body[..body.IndexOf("[autoexec]", StringComparison.OrdinalIgnoreCase)];
            }

            conf.AppendLine($"# --- override: {path} ---");
            conf.AppendLine(body.TrimEnd());
            conf.AppendLine();
        }
        catch (IOException)
        {
            // An unreadable override is not worth blocking the launch over.
        }
    }

    internal static string SafeName(string name)
    {
        var builder = new StringBuilder(name.Length);
        foreach (char c in name)
            builder.Append(char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '_');
        string result = builder.ToString().Trim('_');
        return result.Length == 0 ? "program" : result;
    }

    private static string ShortHash(string value)
    {
        byte[] hash = MD5.HashData(Encoding.UTF8.GetBytes(value.ToLowerInvariant()));
        return Convert.ToHexString(hash)[..8].ToLowerInvariant();
    }
}
