using System.Security.Cryptography;
using System.Text;

namespace ReDOS;

/// <summary>What a generated profile should do once the machine has booted.</summary>
internal sealed record LaunchPlan
{
    /// <summary>Host path of the program to run, or null for a bare DOS prompt.</summary>
    internal string? ProgramPath { get; init; }

    internal IReadOnlyList<string> ProgramArgs { get; init; } = [];

    /// <summary>Use CALL, because a batch file otherwise never returns to our exit line.</summary>
    internal bool AsBatch { get; init; }

    /// <summary>Host folder to expose as drive D: when the program was left outside the sandbox.</summary>
    internal string? ExternalMount { get; init; }

    /// <summary>Keep the machine open after the program ends instead of closing the window.</summary>
    internal bool StayOpen { get; init; }

    /// <summary>Floppy images to put in drive A:. Several become a swappable set (Ctrl+F4).</summary>
    internal IReadOnlyList<string> FloppyImages { get; init; } = [];

    /// <summary>Start on drive A: — what you want when installing from disk 1.</summary>
    internal bool StartOnFloppy { get; init; }

    /// <summary>A hard disk image to attach and boot, for Windows 95/98 and other real systems.</summary>
    internal string? BootImage { get; init; }

    /// <summary>Emulated video adapter for a booted guest, when the default does not suit its driver.</summary>
    internal string? Machine { get; init; }

    /// <summary>Video memory in MB. The guest's driver derives its scanline stride from this.</summary>
    internal int? VideoMemoryMb { get; init; }

    /// <summary>A literal DOS command line to run instead of a program in the sandbox.</summary>
    internal string? RawCommand { get; init; }

    internal string Title { get; init; } = "ReDOS";
}

/// <summary>
/// Writes the machine description handed to the DOS core. Regenerated on every launch; the parts
/// a user is meant to change live in the sandbox (AUTOEXEC.BAT) or in override files.
/// </summary>
internal static class ProfileBuilder
{
    internal static string Build(LaunchPlan plan)
    {
        AppPaths.EnsureDirectories();
        Sandbox.Ensure();

        if (plan.BootImage is not null) return BuildBootProfile(plan);

        var conf = new StringBuilder();
        conf.AppendLine("# Generated by ReDOS. This file is rewritten on every launch -- do not edit.");
        conf.AppendLine("# Persistent tweaks go in:");
        conf.AppendLine($"#   {AppPaths.GlobalOverride}   (every program)");
        conf.AppendLine($"#   {Path.Combine(AppPaths.Overrides, SafeName(plan.Title) + ".conf")}   (this program only)");
        conf.AppendLine("# Startup commands go in the sandbox's own AUTOEXEC.BAT:");
        conf.AppendLine($"#   {Sandbox.AutoexecPath}");
        conf.AppendLine();
        conf.AppendLine("[sdl]");
        conf.AppendLine("fullscreen=false");     // Every program opens in a window; F11+F or alt+enter still toggles.
        conf.AppendLine("autolock=false");
        conf.AppendLine("waitonerror=false");
        conf.AppendLine("output=ttf");           // Text-mode apps look like a normal window; graphics modes switch automatically.
        conf.AppendLine("windowresolution=original");
        conf.AppendLine();
        conf.AppendLine("[ttf]");
        conf.AppendLine("winperc=60");           // Text-mode window covers 60% of the screen: readable, still a window.
        conf.AppendLine();
        conf.AppendLine("[dosbox]");
        conf.AppendLine($"title={plan.Title}");
        conf.AppendLine("startbanner=false");
        conf.AppendLine("quit warning=false");
        conf.AppendLine("memsize=64");
        conf.AppendLine();
        conf.AppendLine("[cpu]");
        conf.AppendLine("core=auto");
        conf.AppendLine("cputype=auto");
        conf.AppendLine("cycles=auto");
        conf.AppendLine();
        conf.AppendLine("[dos]");
        conf.AppendLine("lfn=true");
        conf.AppendLine("ver=7.1");
        conf.AppendLine();
        conf.AppendLine("[render]");
        conf.AppendLine("aspect=true");
        conf.AppendLine();

        AppendOverride(conf, AppPaths.GlobalOverride);
        AppendOverride(conf, Path.Combine(AppPaths.Overrides, SafeName(plan.Title) + ".conf"));

        conf.AppendLine("[autoexec]");
        conf.AppendLine("@echo off");

        conf.AppendLine($"mount c \"{Sandbox.Root}\" -q");
        if (plan.ExternalMount is not null)
            conf.AppendLine($"mount d \"{plan.ExternalMount}\" -q");

        if (plan.FloppyImages.Count > 0)
        {
            // Several images on one drive become a swappable set: Ctrl+F4 changes disk.
            var images = plan.FloppyImages.Select(image => $"\"{image}\"");
            conf.AppendLine($"imgmount a {string.Join(' ', images)} -t floppy");
        }

        conf.AppendLine("c:");
        conf.AppendLine("if exist C:\\AUTOEXEC.BAT call C:\\AUTOEXEC.BAT");

        if (plan.StartOnFloppy)
        {
            conf.AppendLine("a:");
            conf.AppendLine("echo.");
            conf.AppendLine("echo Drive A: holds the floppy. C: is your ReDOS sandbox.");
            if (plan.FloppyImages.Count > 1)
                conf.AppendLine($"echo {plan.FloppyImages.Count} disks loaded - press Ctrl+F4 to change disk.");
            conf.AppendLine("echo Run SETUP or INSTALL to install to C:.");
            conf.AppendLine("echo.");
            conf.AppendLine("dir /w");
        }

        if (plan.RawCommand is not null)
        {
            conf.AppendLine("c:");
            conf.AppendLine(plan.RawCommand);
        }
        else if (plan.ProgramPath is not null)
        {
            string driveLetter = plan.ExternalMount is not null && !Sandbox.Contains(plan.ProgramPath) ? "d" : "c";
            string directory = DosDirectoryOf(plan.ProgramPath, driveLetter);

            conf.AppendLine($"{driveLetter}:");
            conf.AppendLine($"cd \\{directory}".TrimEnd('\\'));
            conf.AppendLine(BuildCommand(plan));
        }

        bool hasCommand = plan.ProgramPath is not null || plan.RawCommand is not null;
        conf.AppendLine(plan.StayOpen || !hasCommand ? "" : "exit");

        string profilePath = Path.Combine(
            AppPaths.Profiles,
            SafeName(plan.Title) + "-" + ShortHash(plan.ProgramPath ?? "prompt") + ".conf");
        File.WriteAllText(profilePath, conf.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return profilePath;
    }

    /// <summary>
    /// A machine for booting a real operating system off a disk image. Almost nothing is shared
    /// with the DOS-program profile: a booted guest drives the hardware itself, so it needs a
    /// graphical adapter, a sound card and an IDE controller rather than a text-mode window.
    /// </summary>
    private static string BuildBootProfile(LaunchPlan plan)
    {
        var conf = new StringBuilder();
        conf.AppendLine("# Generated by ReDOS. This file is rewritten on every launch -- do not edit.");
        conf.AppendLine($"# Persistent tweaks: {Path.Combine(AppPaths.Overrides, SafeName(plan.Title) + ".conf")}");
        conf.AppendLine();
        conf.AppendLine("[sdl]");
        conf.AppendLine("fullscreen=false");
        conf.AppendLine("autolock=true");        // A booted guest owns the mouse, as a real machine would.
        conf.AppendLine("waitonerror=true");
        conf.AppendLine();
        conf.AppendLine("[dosbox]");
        conf.AppendLine($"title={plan.Title}");
        conf.AppendLine($"machine={plan.Machine ?? "svga_s3"}");  // The adapter Windows 9x ships drivers for.
        conf.AppendLine("memsize=64");
        conf.AppendLine("startbanner=false");
        conf.AppendLine("quit warning=false");
        conf.AppendLine();
        conf.AppendLine("[video]");
        // The guest's display driver works out its scanline stride from the video memory it finds.
        // Too little and a mode it was set up for is drawn at the wrong width, repeating across
        // the screen; 8MB covers every mode Windows 9x offers on an S3.
        conf.AppendLine($"vmemsize={plan.VideoMemoryMb ?? 8}");
        conf.AppendLine();
        conf.AppendLine("[cpu]");
        conf.AppendLine("core=dynamic");
        conf.AppendLine("cputype=pentium_mmx");
        conf.AppendLine("cycles=max");
        conf.AppendLine();
        conf.AppendLine("[sblaster]");
        conf.AppendLine("sbtype=sb16");
        conf.AppendLine();
        conf.AppendLine("[ide, primary]");
        conf.AppendLine("enable=true");
        conf.AppendLine();

        AppendOverride(conf, AppPaths.GlobalOverride);
        AppendOverride(conf, Path.Combine(AppPaths.Overrides, SafeName(plan.Title) + ".conf"));

        conf.AppendLine("[autoexec]");
        conf.AppendLine("@echo off");

        // Attaching the image to the IDE controller lets the guest use its own disk drivers instead
        // of falling back to DOS compatibility mode.
        conf.AppendLine($"imgmount c \"{plan.BootImage}\" -t hdd -ide 1m");
        conf.AppendLine("boot -l c");

        string profilePath = Path.Combine(AppPaths.Profiles, SafeName(plan.Title) + "-boot.conf");
        File.WriteAllText(profilePath, conf.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return profilePath;
    }

    /// <summary>Directory part of a program's DOS path, relative to the root of its drive.</summary>
    private static string DosDirectoryOf(string hostPath, string driveLetter)
    {
        string hostDir = Path.GetDirectoryName(Path.GetFullPath(hostPath)) ?? "";
        if (driveLetter == "c" && Sandbox.Contains(hostPath))
        {
            string dosPath = Sandbox.ToDosPath(hostDir);
            return dosPath.Length > 3 ? dosPath[3..] : "";
        }

        // Drive D: is mounted at the program's own folder, so the program sits at its root.
        return "";
    }

    /// <summary>
    /// DOS can only type what fits in 8.3, so prefer the filesystem's short alias and fall back to
    /// the real name (the core's long-filename support covers the rest).
    /// </summary>
    private static string BuildCommand(LaunchPlan plan)
    {
        string name = Path.GetFileName(plan.ProgramPath!);
        string? shortPath = Native.TryGetShortPath(plan.ProgramPath!);
        if (shortPath is not null) name = Path.GetFileName(shortPath);

        var command = new StringBuilder();
        if (plan.AsBatch) command.Append("call ");
        command.Append(name.Contains(' ') ? $"\"{name}\"" : name);

        foreach (string arg in plan.ProgramArgs)
            command.Append(' ').Append(arg.Contains(' ') ? $"\"{arg}\"" : arg);

        return command.ToString();
    }

    private static void AppendOverride(StringBuilder conf, string path)
    {
        if (!File.Exists(path)) return;
        try
        {
            string body = File.ReadAllText(path);
            if (body.Contains("[autoexec]", StringComparison.OrdinalIgnoreCase))
            {
                // An override must not hijack the launch command; ignore its autoexec section.
                body = body[..body.IndexOf("[autoexec]", StringComparison.OrdinalIgnoreCase)];
            }

            conf.AppendLine($"# --- override: {path} ---");
            conf.AppendLine(body.TrimEnd());
            conf.AppendLine();
        }
        catch (IOException)
        {
            // An unreadable override is not worth blocking the launch over.
        }
    }

    internal static string SafeName(string name)
    {
        var builder = new StringBuilder(name.Length);
        foreach (char c in name)
            builder.Append(char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '_');
        string result = builder.ToString().Trim('_');
        return result.Length == 0 ? "program" : result;
    }

    private static string ShortHash(string value)
    {
        byte[] hash = MD5.HashData(Encoding.UTF8.GetBytes(value.ToLowerInvariant()));
        return Convert.ToHexString(hash)[..8].ToLowerInvariant();
    }
}
